# Production Environment - optimized for production deployment
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  frontend:
    environment:
      - NODE_ENV=production
      - API_BASE_URL=https://api.yourdomain.com
    restart: unless-stopped

  invoice-service:
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  tax-calculation-service:
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    deploy:
      replicas: 3 # Scale this service more as it's likely to be heavily used
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  business-entity-service:
    restart: unless-stopped

  zk-proof-service:
    restart: unless-stopped
    deploy:
      replicas: 2 # ZK proof generation might be resource intensive

  validation-service:
    restart: unless-stopped
  # postgres:
  #   environment:
  #     - POSTGRES_DB=tax_calculator_prod
  #     - POSTGRES_USER=prod_user
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  # Use environment variable
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G
  #       reservations:
  #         memory: 1G

  # redis:
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # nginx:
  #   restart: unless-stopped
  #   environment:
  #     - SSL_ENABLED=true
